/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const wasm_bindgen_431eeca2fef2c144___closure__destroy___dyn_core_67558b4ca73dc0a8___ops__function__FnMut__wasm_bindgen_431eeca2fef2c144___JsValue____Output_______: (a: number, b: number) => void;
export const wasm_bindgen_431eeca2fef2c144___closure__destroy___dyn_core_67558b4ca73dc0a8___ops__function__FnMut__core_67558b4ca73dc0a8___option__Option_web_sys_5c4d8ccb72c94769___features__gen_Blob__Blob_____Output_______: (a: number, b: number) => void;
export const wasm_bindgen_431eeca2fef2c144___closure__destroy___dyn_core_67558b4ca73dc0a8___ops__function__FnMut__wasm_bindgen_431eeca2fef2c144___JsValue____Output___core_67558b4ca73dc0a8___result__Result_____wasm_bindgen_431eeca2fef2c144___JsError___: (a: number, b: number) => void;
export const wasm_bindgen_431eeca2fef2c144___closure__destroy___dyn_core_67558b4ca73dc0a8___ops__function__FnMut_____Output_______: (a: number, b: number) => void;
export const wasm_bindgen_431eeca2fef2c144___convert__closures_____invoke___js_sys_11b6d20dd46e6579___Array__web_sys_5c4d8ccb72c94769___features__gen_ResizeObserver__ResizeObserver______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_431eeca2fef2c144___convert__closures_____invoke___wasm_bindgen_431eeca2fef2c144___JsValue__core_67558b4ca73dc0a8___result__Result_____wasm_bindgen_431eeca2fef2c144___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_431eeca2fef2c144___convert__closures_____invoke___wasm_bindgen_431eeca2fef2c144___JsValue______true__1_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_431eeca2fef2c144___convert__closures_____invoke___wasm_bindgen_431eeca2fef2c144___JsValue______true__1__1: (a: number, b: number, c: any) => void;
export const wasm_bindgen_431eeca2fef2c144___convert__closures_____invoke___wasm_bindgen_431eeca2fef2c144___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_431eeca2fef2c144___convert__closures_____invoke___wasm_bindgen_431eeca2fef2c144___JsValue______true__4: (a: number, b: number, c: any) => void;
export const wasm_bindgen_431eeca2fef2c144___convert__closures_____invoke___wasm_bindgen_431eeca2fef2c144___JsValue______true__5: (a: number, b: number, c: any) => void;
export const wasm_bindgen_431eeca2fef2c144___convert__closures_____invoke___wasm_bindgen_431eeca2fef2c144___JsValue______true__6: (a: number, b: number, c: any) => void;
export const wasm_bindgen_431eeca2fef2c144___convert__closures_____invoke___wasm_bindgen_431eeca2fef2c144___JsValue______true__7: (a: number, b: number, c: any) => void;
export const wasm_bindgen_431eeca2fef2c144___convert__closures_____invoke___wasm_bindgen_431eeca2fef2c144___JsValue______true__8: (a: number, b: number, c: any) => void;
export const wasm_bindgen_431eeca2fef2c144___convert__closures_____invoke___wasm_bindgen_431eeca2fef2c144___JsValue______true__9: (a: number, b: number, c: any) => void;
export const wasm_bindgen_431eeca2fef2c144___convert__closures_____invoke___wasm_bindgen_431eeca2fef2c144___JsValue______true__10: (a: number, b: number, c: any) => void;
export const wasm_bindgen_431eeca2fef2c144___convert__closures_____invoke___core_67558b4ca73dc0a8___option__Option_web_sys_5c4d8ccb72c94769___features__gen_Blob__Blob_______true_: (a: number, b: number, c: number) => void;
export const wasm_bindgen_431eeca2fef2c144___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const wasm_bindgen_431eeca2fef2c144___convert__closures_____invoke_______true__1_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
